### ISSUE TITLE
Similar python LBLRTM utilities

### ISSUE THREAD

**Issue by wblumberg** [pernak18/common#1]
Hi there - I'm a long time user of the LBLRTM (I worked with Dave Turner during my time in graduate school).  I wanted to ask if there was any addition planned development of this repository (documentation, test cases, etc.).  I use a lot of Python (as does the larger community) and just stumbled upon the fact that many of AER's programs are now on Github.  I'm excited to see it online here as Github has so many tools available to help the development and sharing of code.

As an aside, I wanted to point y'all to my repository hosting LBLRTM python utilities similar to this repository (https://github.com/wblumberg/PyLBLRTM). It looks like this repository is a little more complete than mine, but if there's anything from my repository that can be added here, please use it!  I've had a lot of interest over the years in my repository, but I don't have a lot of time to develop it anymore.

**Comment by pernak18** [comment]
thanks @wblumberg! we are very close to migrating the rest of AER's RTWeb into GitHub, so stay tuned for things like RRTM, RADSUM, monoRTM, and solar irradiance. containerizing everything is also on my list (already done with [LBLRTM v12.9](https://github.com/AER-RC/LBLRTM/packages/200551)). also note our entire Line File Parameters "database" is available publicly in [Zenodo](https://zenodo.org/record/4019086)

if by "this" repository, you mean [common utilities](https://github.com/AER-RC/common), i should add some use cases. but more development will occur in the actual model repositories like [LBLRTM](https://github.com/AER-RC/LBLRTM). be sure to have a look at their `README.md` and Wiki pages. with LBL, we have a set of "run examples" that end users can treat as validation baselines -- see the [v12.10 release](https://github.com/AER-RC/LBLRTM/releases/tag/v12.10).

i'm the only Pythoner in our AER-RC group, so your repo may not pique the interest of the 'higher-ups', but it's great to hear that others are using your code. should the opportunity present itself, i look forward to perusing your code rather than FORTRAN (editor's note: @pernak18 hates FORTRAN)

thank you for your interest in our models!
