### ISSUE TITLE
Python3 Compatibility

### ISSUE THREAD

**Issue by varisht-tathya** [pernak18/common#3]
I was trying to utilize the "writeTape5" method from lblTools.py script file. Even though the script says it is compatible with Python 3 it throws errors for me while writing the files. I have tried with python 3.7, 3.8. I even tried the automated Python 2 to python 3 conversion, and it still fails to write the files.

**Comment by pernak18** [comment]
@varisht-tathya sorry for the very delayed response (i did not get an automated email notification from GitHub). 

`TAPE5` files are very _ad-hoc_, so that function exists for a specific application for someone else at AER. i would not recommend using it, and i have not attempted to modernize it. the only reason `lblTools.py` is in version control is for the output readers, which are much more standardized (and even then, i cannot promise Python 3 compatibility).
