### ISSUE TITLE
readTAPE7 will return 0 for p_lay due to indexing issues

### ISSUE THREAD

**Issue by mcduffie** [pernak18/common#5]
In the readTAPE7 routine of RC_utils.py

There is an indexing bug when reading pLay from the TAPE7 file.

The line:
    ipLay = np.array([10])
Should be:
    ipLay = np.array([0, 10])

And 
    ipLay = np.array([15])
should be:
    ipLay = np.array([0, 15])

This was fixed in different version of RC_utils.py that had been a submodule at least through Aug 30 2018.

**Comment by pernak18** [comment]
thanks @mcduffie.

right...i saw this bug after our ABSCO project together and addressed it with 750a365f3a25aa7ebead24e89774a419b393f2fe, i believe. lots has happened since that commit as well, so i have updated with `master` and branched off onto [`refractor`](https://github.com/AER-RC/common/tree/refractor), which includes all of the bug fixes we have done in the time span you mentioned. ABSCO now points to this branch instead of a random commit on `master`.

let us know if this fixes the issue you found.

please and thanks

**Comment by mcduffie** [comment]
That fixes that bug.Should have reported in the other repo, sorry.
